version: '3.8'

services:
  backend:
    build: 
      context: .
    tty: true
     
    command: >
      sh -c "python -m pip install --upgrade pip && pip install django && pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db
    
  db:
    image: postgres:14
    ports:
      - 5432:5432
    
    
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: