# Generated by Django 5.0.4 on 2024-04-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testrestapi2', '0002_delete_historyapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cad_num', models.CharField()),
                ('shirota', models.CharField()),
                ('dolgota', models.CharField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('result', models.BooleanField()),
            ],
        ),
    ]
